// Generated by CoffeeScript 1.6.2
(function() {
  var $, contentElement, makeIndexForHeadings;

  $ = jQuery;

  contentElement = null;

  makeIndexForHeadings = function(headings) {
    var indexContainer, list, scrollToHeading;

    contentElement.append(indexContainer = $('<nav>', {
      "class": 'headingIndex'
    }));
    indexContainer.append(list = $('<ul>').on('click a', function(event) {
      return scrollToHeading($(event.target).parent().index());
    }));
    headings.each(function() {
      return list.append($('<li>').append($('<a>', {
        href: 'javascript:',
        html: this.innerHTML
      })));
    });
    indexContainer;
    return scrollToHeading = function(indexOrSlug) {};
  };

  $(function() {
    var headings;

    contentElement = $('article > div.content');
    if (contentElement.height() > document.documentElement.clientHeight) {
      headings = contentElement.find('h2');
      if (headings.size() > 1) {
        makeIndexForHeadings(headings);
      }
    }
  });

}).call(this);
