// Generated by CoffeeScript 1.6.2
(function() {
  var $, containerStyle, docElem, fixSidebarBgHeight, sidebarBgStyle;

  $ = jQuery;

  containerStyle = null;

  sidebarBgStyle = null;

  docElem = document.documentElement;

  fixSidebarBgHeight = function() {
    containerStyle.height = '100%';
    if (docElem.scrollHeight > docElem.clientHeight) {
      containerStyle.height = docElem.scrollHeight + 'px';
    }
    sidebarBgStyle.width = Math.max(500, docElem.clientWidth / 2) + 'px';
  };

  $(window).on('resize', fixSidebarBgHeight);

  $(function() {
    var activeClass, activeUri, patterns, submit, validate;

    containerStyle = $('.n13-background')[0].style;
    sidebarBgStyle = $('.n13-sidebar-bg')[0].style;
    fixSidebarBgHeight();
    activeClass = 'n13-active';
    activeUri = document.location.href.replace(/\?.*/, '').replace(/^\w+:\/\/|\/$/g, '');
    $('.n13-body a').each(function() {
      var $el, $parent;

      if (this.href.replace(/^\w+:\/\/|\/$/g, '') === activeUri) {
        $el = $(this).addClass(activeClass);
        $parent = $el.parent();
        if ($parent.is('li')) {
          $parent.addClass(activeClass);
        }
      }
    });
    $('.n13-posts').on('click .article', function(e) {
      document.location = $(e.target).parents('article').find('h2 a').attr('href');
    });
    $('#respond form > input').prependTo('#respond form p.form-submit');
    submit = $('<form>')[0].submit;
    $('input[type=submit]').each(function() {
      var form, old;

      old = $(this);
      form = old.parents('form');
      old.after($('<a>', {
        href: 'javascript:',
        text: old.val(),
        "class": 'submit'
      }).on('click', function() {
        if (validate.call(form[0])) {
          submit.call(form.append($('<input>', {
            type: 'hidden',
            name: old.attr('name'),
            value: old.val()
          }))[0]);
        }
      })).remove();
    });
    patterns = {
      comment: /\w{5,}/,
      author: /\w{2,}/,
      email: /.+@.+\..+/
    };
    validate = function() {
      var errors, id, pattern;

      errors = [];
      for (id in patterns) {
        pattern = patterns[id];
        if (this[id] && !pattern.exec(this[id].value)) {
          errors.push("Value for " + this[id].placeholder + " is invalid.");
        }
      }
      if (errors.length) {
        alert(errors.join("\n"));
      }
      return !errors.length;
    };
    $('form').on('submit', validate);
  });

}).call(this);
