// Generated by CoffeeScript 1.6.2
(function() {
  var $, containerStyle, docElem, fixSidebarBgHeight, sidebarBgStyle;

  $ = jQuery;

  containerStyle = null;

  sidebarBgStyle = null;

  docElem = document.documentElement;

  fixSidebarBgHeight = function() {
    containerStyle.height = '100%';
    if (docElem.scrollHeight > docElem.clientHeight) {
      containerStyle.height = docElem.scrollHeight + 'px';
    }
    sidebarBgStyle.width = Math.max(500, docElem.clientWidth / 2) + 'px';
  };

  $(window).on('resize', fixSidebarBgHeight);

  $(function() {
    var activeClass, activeUri;

    containerStyle = $('.n13-container')[0].style;
    sidebarBgStyle = $('.n13-sidebar-bg')[0].style;
    fixSidebarBgHeight();
    activeClass = 'n13-active';
    activeUri = document.location.href.replace(/\?.*/, '').replace(/^\w+:\/\/|\/$/g, '');
    console.log(activeUri);
    $('.n13-body a').each(function() {
      var $el, $parent;

      if (this.href.replace(/^\w+:\/\/|\/$/g, '') === activeUri) {
        $el = $(this).addClass(activeClass);
        $parent = $el.parent();
        if ($parent.is('li')) {
          $parent.addClass(activeClass);
        }
      }
    });
  });

}).call(this);
