// Generated by CoffeeScript 1.6.2
(function() {
  var $, docElem, fixSidebarBgHeight, sidebarBgStyle;

  $ = jQuery;

  sidebarBgStyle = null;

  docElem = document.documentElement;

  fixSidebarBgHeight = function() {
    sidebarBgStyle.height = 'auto';
    if (docElem.scrollHeight > docElem.clientHeight) {
      sidebarBgStyle.height = docElem.scrollHeight + 'px';
    }
  };

  $(function() {
    sidebarBgStyle = $('.neil2013-sidebar-bg')[0].style;
    fixSidebarBgHeight();
  });

  $(window).on('resize', fixSidebarBgHeight);

}).call(this);
